/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/kXGwht6fSst
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/

"use client"
import { Card } from "@/components/ui/card"
import { ResponsiveLine } from "@nivo/line"



export default function PeuTemps() {

return (
    <div className="flex flex-col gap-6 p-6 md:p-8 lg:p-10">
      <div className="grid grid-cols-2 gap-6 md:grid-cols-4">
        <Card className="flex flex-col gap-2 p-4 bg-white dark:bg-gray-950 rounded-lg shadow-sm">
          <div className="flex items-center justify-between">
            <div className="text-lg font-medium">Temperature</div>
            <ThermometerIcon className="w-6 h-6 text-red-500" />
          </div>
          <div className="text-4xl font-bold">°C</div>
          <div
            className="h-2 rounded-full"
            style={{
              width: "%",
            }}
          />
        </Card>
        <Card className="flex flex-col gap-2 p-4 bg-white dark:bg-gray-950 rounded-lg shadow-sm">
          <div className="flex items-center justify-between">
            <div className="text-lg font-medium">Humidity</div>
            <DropletIcon className="w-6 h-6 text-blue-500" />
          </div>
          <div className="text-4xl font-bold">%</div>
          <div
            className="h-2 rounded-full"
            style={{
              width: "%",
            }}
          />
        </Card>
        <Card className="flex flex-col gap-2 p-4 bg-white dark:bg-gray-950 rounded-lg shadow-sm">
          <div className="flex items-center justify-between">
            <div className="text-lg font-medium">Temperature</div>
            <div className="flex items-center gap-1">
              <ArrowUpIcon className="w-4 h-4 text-green-500" />
              <span className="text-green-500">°C</span>
            </div>
          </div>
          <div className="flex items-center justify-between">
            <div className="text-lg font-medium">Humidity</div>
            <div className="flex items-center gap-1">
              <ArrowUpIcon className="w-4 h-4 text-green-500" />
              <span className="text-green-500">%</span>
            </div>
          </div>
        </Card>
        <Card className="flex flex-col gap-2 p-4 bg-white dark:bg-gray-950 rounded-lg shadow-sm">
          <div className="flex items-center justify-between">
            <div className="text-lg font-medium">Temperature</div>
            <div className="flex items-center gap-1">
              <ArrowDownIcon className="w-4 h-4 text-red-500" />
              <span className="text-red-500">°C</span>
            </div>
          </div>
          <div className="flex items-center justify-between">
            <div className="text-lg font-medium">Humidity</div>
            <div className="flex items-center gap-1">
              <ArrowDownIcon className="w-4 h-4 text-red-500" />
              <span className="text-red-500">%</span>
            </div>
          </div>
        </Card>
      </div>
      <Card className="flex flex-col gap-4 p-4 bg-white dark:bg-gray-950 rounded-lg shadow-sm">
        <div className="flex items-center justify-between">
          <div className="text-lg font-medium">Temperature and Humidity</div>
          <div className="flex items-center gap-2">
            <div className="flex items-center gap-1 text-red-500">
              <ThermometerIcon className="w-4 h-4" />
              <span>Temperature</span>
            </div>
            <div className="flex items-center gap-1 text-blue-500">
              <DropletIcon className="w-4 h-4" />
              <span>Humidity</span>
            </div>
          </div>
        </div>
        <TimeseriesChart className="aspect-[16/9]" />
      </Card>
      <div className="grid grid-cols-2 gap-6 md:grid-cols-4">
        <Card className="flex flex-col gap-2 p-4 bg-white dark:bg-gray-950 rounded-lg shadow-sm">
          <div className="text-lg font-medium">Temperature</div>
          <div className="text-4xl font-bold">°C</div>
          <div className="text-sm text-gray-500 dark:text-gray-400">Average</div>
        </Card>
        <Card className="flex flex-col gap-2 p-4 bg-white dark:bg-gray-950 rounded-lg shadow-sm">
          <div className="text-lg font-medium">Humidity</div>
          <div className="text-4xl font-bold">%</div>
          <div className="text-sm text-gray-500 dark:text-gray-400">Average</div>
        </Card>
      </div>
    </div>
  )
}

function ArrowDownIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M12 5v14" />
      <path d="m19 12-7 7-7-7" />
    </svg>
  )
}


function ArrowUpIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m5 12 7-7 7 7" />
      <path d="M12 19V5" />
    </svg>
  )
}


function DropletIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M12 22a7 7 0 0 0 7-7c0-2-1-3.9-3-5.5s-3.5-4-4-6.5c-.5 2.5-2 4.9-4 6.5C6 11.1 5 13 5 15a7 7 0 0 0 7 7z" />
    </svg>
  )
}


function ThermometerIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M14 4v10.54a4 4 0 1 1-4 0V4a2 2 0 0 1 4 0Z" />
    </svg>
  )
}


function TimeseriesChart(props) {
  return (
    <div {...props}>
      <ResponsiveLine
        data={[
          {
            id: "Desktop",
            data: [
              { x: "2018-01-01", y: 7 },
              { x: "2018-01-02", y: 5 },
              { x: "2018-01-03", y: 11 },
              { x: "2018-01-04", y: 9 },
              { x: "2018-01-05", y: 12 },
              { x: "2018-01-06", y: 16 },
              { x: "2018-01-07", y: 13 },
            ],
          },
          {
            id: "Mobile",
            data: [
              { x: "2018-01-01", y: 9 },
              { x: "2018-01-02", y: 8 },
              { x: "2018-01-03", y: 13 },
              { x: "2018-01-04", y: 6 },
              { x: "2018-01-05", y: 8 },
              { x: "2018-01-06", y: 14 },
              { x: "2018-01-07", y: 11 },
            ],
          },
        ]}
        margin={{ top: 10, right: 20, bottom: 40, left: 40 }}
        xScale={{
          type: "time",
          format: "%Y-%m-%d",
          useUTC: false,
          precision: "day",
        }}
        xFormat="time:%Y-%m-%d"
        yScale={{
          type: "linear",
          min: 0,
          max: "auto",
        }}
        axisTop={null}
        axisRight={null}
        axisBottom={{
          tickSize: 0,
          tickPadding: 16,
          format: "%d",
          tickValues: "every 1 day",
        }}
        axisLeft={{
          tickSize: 0,
          tickValues: 5,
          tickPadding: 16,
        }}
        colors={["#2563eb", "#e11d48"]}
        pointSize={6}
        useMesh={true}
        gridYValues={6}
        theme={{
          tooltip: {
            chip: {
              borderRadius: "9999px",
            },
            container: {
              fontSize: "12px",
              textTransform: "capitalize",
              borderRadius: "6px",
            },
          },
          grid: {
            line: {
              stroke: "#f3f4f6",
            },
          },
        }}
        role="application"
      />
    </div>
  )
}
